import argparse


def setup_parser():
    parser = argparse.ArgumentParser()
    parser.add_argument('--path_to_set', default=None, type=str)
    parser.add_argument('--path_to_results', default=None, type=str)
    parser.add_argument('--path_to_trained_model', default=None, type=str)
    parser.add_argument('--amount_of_files', default=None, type=int)
    parser.add_argument('--amount_of_slices', default=None, type=int)
    parser.add_argument('--channels', default=16, type=int)
    parser.add_argument('--batch_size', default=None, type=int)
    parser.add_argument('--valid_batch_size', default=None, type=int)
    parser.add_argument('--total_samples', default=None, type=int)
    parser.add_argument('--title', default=None, type=str)
    parser.add_argument('--use_db', default=False, type=bool)
    parser.add_argument('--gpu_device', default=None,type=str)
    parser.add_argument('--loss', default='rel', type=str)
    parser.add_argument('--use_ssim_loss', default=False, type=bool)
    parser.add_argument('--cross_validation_fold', default=None, type=int)
    parser.add_argument('--debug_mode', default=False, type=bool)
    parser.add_argument('--patch_size', default=64, type=int)
    parser.add_argument('--epochs', default=None, type=int)
    parser.add_argument('--scheduler', default='const', type=str,choices=['const', 'Plateau', 'Multiplicative'])
    parser.add_argument('--lr_g', default=None, type=float)
    parser.add_argument('--lr_d', default=None, type=float)
    parser.add_argument('--load_to_memory', default=False, type=bool)
    parser.add_argument('--max_workers_train', default=None, type=int)
    parser.add_argument('--max_workers_valid', default=None, type=int)
    parser.add_argument('--val_epoch', default=None, type=int)
    parser.add_argument('--multiprocess', default=False, type=bool)
    parser.add_argument('--random_patches', default=False, type=bool)
    parser.add_argument('--no_train',  default=False, type=bool)
    parser.add_argument('--no_valid',  default=False, type=bool)
    parser.add_argument('--adversarial_weight_I', default=None, type=float)
    parser.add_argument('--adversarial_weight_E', default=None, type=float)
    parser.add_argument('--use_ddp', action='store_true')
    parser.add_argument('--set_seed', default=24, type=int)
    parser.add_argument('--sig_flag', default=False, type=bool)
    parser.add_argument('--d_optimizer_step_size', default=None, type=int)
    parser.add_argument('--g_optimizer_step_size', default=None, type=int)
    parser.add_argument('--test_mode', default=False, type=bool)
    parser.add_argument('--image_save_freq_batch', default=100, type=int)
    parser.add_argument('--image_save_freq_epoch', default=100, type=int)
    parser.add_argument('--augmentation_state', default=False, type=bool)
    parser.add_argument('--cheakpoint_epoch', default=[], type=int,nargs='*')
    parser.add_argument('--transfer_learning', default=False, type=bool)
    return parser